### ISSUE TITLE
Getting `TypeError: wrong argument type JSON::Pure::Generator::State (expected Data)` from json/pure when called Hash.`to_json`  with Fixnum data

### ISSUE THREAD

**Issue by johnvoloski** [ruby/json#198] opened 2014-03-07 14:38 UTC
``` ruby
some_hash = { 'jsonrpc' => 'xxxx', 'jsonversion' => 1 }
some_hash.to_json

wrong argument type JSON::Pure::Generator::State(expected Data) (TypeError)
```

I solved the problem implementing:
`lib/json/pure/generator.rb:413`

``` ruby
class Fixnum
  def to_json(*) to_s end
end
```

**Comment by byroot** [comment] 2024-10-17 20:02
Duplicate of https://github.com/ruby/json/issues/186

**Closed by byroot** 2024-10-17 20:02 UTC
